version: "3.4"

x-services: &env
  env_file:
    - ${ENV:-testnet}.env

services:
  backend:
    <<: *env
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - NEAR_EXPLORER_WAMP_PORT=8080
      - NEAR_EXPLORER_WAMP_HOST=wamp
      - NEAR_EXPLORER_WAMP_BACKEND_SECRET=THIS_IS_LOCALHOST_SECRET
    mem_limit: 1G
    entrypoint: ["npm", "run", "start"]
    ports:
      - 10000:10000

  frontend:
    <<: *env
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - PORT=3000
      - NEAR_EXPLORER_WAMP_HOST=localhost
      - NEAR_EXPLORER_WAMP_SSR_HOST=wamp
      - NEAR_EXPLORER_WAMP_SSR_PORT=8080
      - NEAR_EXPLORER_WAMP_BACKEND_SECRET=THIS_IS_LOCALHOST_SECRET
    ports:
      - 3000:3000
    command: ["npm", "run", "start"]
