version: "2"

services:
  wamp:
    build: ./wamp
    environment:
      - NEAR_EXPLORER_WAMP_BACKEND_SECRET=THIS_IS_LOCALHOST_SECRET
    ports:
      - 10000:8080

  backend:
    build: ./backend
    environment:
      - NEAR_EXPLORER_WAMP_HOST=wamp
      - NEAR_EXPLORER_WAMP_BACKEND_SECRET=THIS_IS_LOCALHOST_SECRET
    mem_limit: 1G
    entrypoint: ["npm", "run", "start:testnet"]

  frontend:
    build: ./frontend
    environment:
      - PORT=3000
      - NEAR_EXPLORER_WAMP_HOST=localhost
      - NEAR_EXPLORER_WAMP_BACKEND_SECRET=THIS_IS_LOCALHOST_SECRET
    ports:
      - 3000:3000
    command: ["npm", "run", "start:local-wamp-testnet"]
