version: '2'

services:
  wamp:
    build: ./wamp
    environment:
      - WAMP_NEAR_EXPLORER_PORT=8080
      - WAMP_NEAR_EXPLORER_BACKEND_SECRET=back
    ports:
      - 8080:8080

  backend:
    build: ./backend
    environment:
      - WAMP_NEAR_EXPLORER_URL=ws://wamp:8080/ws
      - WAMP_NEAR_EXPLORER_BACKEND_SECRET=back
    mem_limit: 1G
    entrypoint: ["npm", "run", "start:testnet-with-indexer"]

  frontend:
    build: ./frontend
    environment:
      - PORT=3000
      - WAMP_NEAR_EXPLORER_URL=ws://localhost:8080/ws
      - WAMP_NEAR_EXPLORER_INTERNAL_URL=ws://wamp:8080/ws
    ports:
      - 3000:3000
    command: ["npm", "run", "start:local-wamp-with-indexer-testnet"]
