version: '3'

services:
  wamp:
    build: ./wamp
    environment:
      - WAMP_NEAR_EXPLORER_PORT=8080
      - WAMP_NEAR_EXPLORER_BACKEND_SECRET=back
    ports:
      - 8080:8080

  backend:
    build: ./backend
    environment:
      - NEAR_RPC_URL=https://rpc.devnet.nearprotocol.com
      #- NEAR_RPC_URL=https://rpc.betanet.nearprotocol.com
      # - NEAR_RPC_URL=https://rpc.testnet.nearprotocol.com
      - WAMP_NEAR_EXPLORER_URL=ws://wamp:8080/ws
      - WAMP_NEAR_EXPLORER_BACKEND_SECRET=back

  frontend:
    build: ./frontend
    environment:
      - PORT=3000
      - WAMP_NEAR_EXPLORER_URL=ws://localhost:8080/ws
      - WAMP_NEAR_EXPLORER_INTERNAL_URL=ws://wamp:8080/ws
    ports:
      - 3000:3000
